# ----------------------------------------------------------------------
# |
# |  action.yml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2024-01-21 14:12:29
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2024
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "[impl] Validate"
description: "Validates the current repository"

inputs:
  operating_system:
    required: true
    type: string

  python_version:
    required: true
    type: string

  script_prefix:
    required: true
    type: string

  script_extension:
    required: true
    type: string

  shell_name:
    required: true
    type: string

  source_command:
    required: true
    type: string

  sudo_command:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Bootstrap
      shell: ${{ inputs.shell_name }}
      run: |
        ${{ inputs.script_prefix }}Bootstrap${{ inputs.script_extension }} --python-version ${{ inputs.python_version }}

    - name: Black
      shell: ${{ inputs.shell_name }}
      run: |
        ${{ inputs.source_command }} ${{ inputs.script_prefix }}Activate${{ inputs.script_extension }}
        python Build.py black

    - name: Pylint
      shell: ${{ inputs.shell_name }}
      run: |
        ${{ inputs.source_command }} ${{ inputs.script_prefix }}Activate${{ inputs.script_extension }}
        python Build.py pylint

    - name: Pytest
      shell: ${{ inputs.shell_name }}
      run: |
        ${{ inputs.source_command }} ${{ inputs.script_prefix }}Activate${{ inputs.script_extension }}
        python Build.py pytest --code-coverage
