# ----------------------------------------------------------------------
# |
# |  action.yml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2024-02-01 11:26:45
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2024
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "[impl] Validates Python Binary"
description: "Validates a Python binary"

inputs:
  operating_system:
    required: true
    type: string

  python_version:
    required: true
    type: string

  validation_command:
    required: true
    type: string

  shell_name:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: stage
        pattern: python_binary-${{ inputs.operating_system }}-${{ inputs.python_version }}

    - name: Validate (Windows)
      if: ${{ startsWith(inputs.operating_system, 'windows') }}
      shell: ${{ inputs.shell_name }}
      run: |
        for /r stage %%F in (exe.*-${{ inputs.python_version }}.zip) do (
            echo Expanding "%%F"...
            PowerShell -Command "Expand-Archive -Path '%%F' -DestinationPath ."
            echo.
            echo.

            ${{ inputs.validation_command }}
        )

    - name: Validate (Standard)
      if: ${{ ! startsWith(inputs.operating_system, 'windows') }}
      shell: ${{ inputs.shell_name }}
      run: |
        archive_filename=$(find ./stage -name "exe.*-${{ inputs.python_version }}.tar.gz")

        tar --extract --file "${archive_filename}" --gunzip --verbose
        echo ""
        echo ""

        ./${{ inputs.validation_command }}
