# ----------------------------------------------------------------------
# |
# |  action.yml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2024-01-26 21:38:23
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2024
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "[impl] Publish"
description: "Publishes the current repository"

inputs:
  script_prefix:
    required: true
    type: string

  script_extension:
    required: true
    type: string

  shell_name:
    required: true
    type: string

  source_command:
    required: true
    type: string

  sudo_command:
    required: true
    type: string

  pypi_token:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: stage

    - name: Bootstrap
      shell: ${{ inputs.shell_name }}
      run: |
        ${{ inputs.script_prefix }}Bootstrap${{ inputs.script_extension }} --package

    - name: Organize Artifacts
      shell: ${{ inputs.shell_name }}
      id: organize_artifacts
      run: |
        curl --location https://raw.githubusercontent.com/davidbrownell/dbrownell_DevTools/main/.github/tools/OrganizePythonArtifacts.py --output OrganizePythonArtifacts.py --no-progress-meter --fail-with-body

        ${{ inputs.source_command }} ${{ inputs.script_prefix }}Activate${{ inputs.script_extension }}
        python OrganizePythonArtifacts.py ./stage ./dist

        echo "python_version=$(cat ./dist/__version__)" >> $GITHUB_OUTPUT

    - name: Publish
      shell: ${{ inputs.shell_name }}
      run: |
        ${{ inputs.source_command }} ${{ inputs.script_prefix }}Activate${{ inputs.script_extension }}
        python Build.py publish ${{ inputs.pypi_token }} --production --verbose

    - name: Create Tag
      shell: ${{ inputs.shell_name }}
      run: |
        git config user.name "GitHub Action Bot"
        git config user.email "<>"

        git tag --annotate --force -m "Publish Tag" "v${{ steps.organize_artifacts.outputs.python_version }}" "${{ github.sha }}"
        git push origin "v${{ steps.organize_artifacts.outputs.python_version }}" --force

    - name: Create GitHub Release
      shell: ${{ inputs.shell_name }}
      run: |
        gh release create "v${{ steps.organize_artifacts.outputs.python_version }}"

        for filename in ./dist/*; do
            if [[ -f ${filename} ]]; then
              gh release upload "v${{ steps.organize_artifacts.outputs.python_version }}" "${filename}" --clobber
            fi
        done
