# ----------------------------------------------------------------------
# |
# |  action.yml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2024-02-01 11:23:39
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2024
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "[impl] Build Binary"
description: "Builds a binary within the current repository"

inputs:
  operating_system:
    required: true
    type: string

  python_version:
    required: true
    type: string

  script_prefix:
    required: true
    type: string

  script_extension:
    required: true
    type: string

  shell_name:
    required: true
    type: string

  source_command:
    required: true
    type: string

  sudo_command:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Bootstrap
      shell: ${{ inputs.shell_name }}
      run: |
        ${{ inputs.script_prefix }}Bootstrap${{ inputs.script_extension }} --python-version ${{ inputs.python_version }} --package

    - name: Update Version
      shell: ${{ inputs.shell_name }}
      run: |
        ${{ inputs.source_command }} ${{ inputs.script_prefix }}Activate${{ inputs.script_extension }}
        python Build.py update_version --verbose

    - name: Build Binary
      shell: ${{ inputs.shell_name }}
      run: |
        ${{ inputs.source_command }} ${{ inputs.script_prefix }}Activate${{ inputs.script_extension }}
        python Build.py build_binary --verbose

    # Note that we have to create the archive to preserve execute permissions (see https://github.com/actions/upload-artifact/issues/38 for more info)
    - name: Create Archive
      shell: ${{ inputs.shell_name }}
      run: |
        curl --location https://raw.githubusercontent.com/davidbrownell/dbrownell_DevTools/main/.github/tools/CreatePythonBinaryArchive.py --output CreatePythonBinaryArchive.py --no-progress-meter --fail-with-body

        ${{ inputs.source_command }} ${{ inputs.script_prefix }}Activate${{ inputs.script_extension }}
        python CreatePythonBinaryArchive.py archive

    - name: Upload Archive
      uses: actions/upload-artifact@v4
      with:
        name: "python_binary-${{ inputs.operating_system }}-${{ inputs.python_version }}"
        path: archive
        compression-level: 0
