# ----------------------------------------------------------------------
# |
# |  action.yml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2024-02-15 13:05:27
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2024
# |  Distributed under the MIT License.
# |
# ----------------------------------------------------------------------
name: "[impl] Create Docker Image"
description: "Creates a Docker image within the current repository"

inputs:
  name_suffix:
    required: false
    type: string
    default: ""

  docker_description:
    required: true
    type: string

  bootstrap_args:
    required: true
    type: string

  push_image_as_package:
    required: false
    type: boolean
    default: false

  container_registry_password:
    required: false
    type: string

  operating_system:
    required: true
    type: string

  python_version:
    required: true
    type: string

  script_prefix:
    required: true
    type: string

  script_extension:
    required: true
    type: string

  shell_name:
    required: true
    type: string

  source_command:
    required: true
    type: string

  compressed_extension:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Bootstrap
      shell: ${{ inputs.shell_name }}
      run: |
        ${{ inputs.script_prefix }}Bootstrap${{ inputs.script_extension }} --python-version ${{ inputs.python_version }} --package

    - name: Create Docker Image
      shell: ${{ inputs.shell_name }}
      run: |
        ${{ inputs.source_command }} ${{ inputs.script_prefix }}Activate${{ inputs.script_extension }}
        python Build.py create_docker_image --name-suffix "${{ inputs.name_suffix }}" --description "${{ inputs.docker_description }}" --bootstrap-args "${{ inputs.bootstrap_args }}" --verbose

    - name: Get Image Name
      id: image_name
      shell: ${{ inputs.shell_name }}
      run: |
        echo "IMAGE_NAME=$(docker images --format {{.Repository}}:{{.Tag}} | awk 'NR==1')" >> $GITHUB_OUTPUT

    - name: Save Docker Image
      shell: ${{ inputs.shell_name }}
      run: |
        ${{ inputs.source_command }} ${{ inputs.script_prefix }}Activate${{ inputs.script_extension }}

        python -c "
        import sys
        from pathlib import Path

        from dbrownell_Common.Streams.DoneManager import DoneManager
        from dbrownell_DevTools import BuildActivities

        with DoneManager.Create(sys.stdout, 'Saving...') as dm:
            BuildActivities.SaveDockerImage(
                dm,
                '${{ steps.image_name.outputs.IMAGE_NAME }}',
                Path('./docker_image${{ inputs.name_suffix }}.tar${{ inputs.compressed_extension }}'),
            )
        "

    - name: Upload Docker Image
      uses: actions/upload-artifact@v4
      with:
        name: docker_image${{ inputs.name_suffix }}.tar${{ inputs.compressed_extension }}
        path: docker_image${{ inputs.name_suffix }}.tar${{ inputs.compressed_extension }}

    - name: Log in to the Container registry
      if: ${{ inputs.push_image_as_package && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.container_registry_password }}

    - name: Push Docker Image
      if: ${{ inputs.push_image_as_package && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      shell: ${{ inputs.shell_name }}
      run: |
        ${{ inputs.source_command }} ${{ inputs.script_prefix }}Activate${{ inputs.script_extension }}

        python -c "
        import sys

        from dbrownell_Common.Streams.DoneManager import DoneManager
        from dbrownell_DevTools import BuildActivities

        with DoneManager.Create(sys.stdout, 'Pushing...') as dm:
            BuildActivities.PushDockerImage(
                dm,
                '${{ steps.image_name.outputs.IMAGE_NAME }}',
                'ghcr.io',
                '${{ github.actor }}',
            )
        "
