# ----------------------------------------------------------------------
# |
# |  callable_validate_python_binary.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2024-02-01 10:12:32
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2024
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "[impl] Validates Python Binary"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      operating_system:
        required: true
        type: string

      python_version:
        required: true
        type: string

      binary_name:
        required: true
        type: string

      validation_command:
        required: true
        type: string

jobs:
  validate:
    name: Execute
    runs-on: ${{ inputs.operating_system }}

    steps:
      - name: Initialize
        id: Initialize
        uses: davidbrownell/dbrownell_DevTools/.github/actions/initialize@main
        with:
          operating_system: ${{ inputs.operating_system }}

      - name: Validate Package
        uses: davidbrownell/dbrownell_DevTools/.github/actions/validate_python_binary_impl@main
        with:
          operating_system: ${{ inputs.operating_system }}
          python_version: ${{ inputs.python_version }}
          package_name: ${{ inputs.package_name }}
          validation_command: ${{ inputs.validation_command }}
          shell_name: ${{ steps.initialize.outputs.shell_name }}
