# ----------------------------------------------------------------------
# |
# |  callable_validate_python.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2024-01-27 10:50:29
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2024
# |  Distributed under the MIT License.
# |
# ----------------------------------------------------------------------
name: "[Callable] Validate Python changes"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      operating_system:
        required: true
        type: string

      python_version:
        required: true
        type: string

    secrets:
      CUSTOM_INITIALIZATION_SECRET:
        required: false

jobs:
  validate:
    name: Execute
    runs-on: ${{ inputs.operating_system }}

    env:
      COLUMNS: "200"
      SIMULATE_TERMINAL_CAPABILITIES_SUPPORTS_COLORS: "1"
      PYTHONIOENCODING: "UTF-8"
      COVERAGE_FILE: .coverage.${{ inputs.operating_system }}.${{ inputs.python_version }}

    permissions: {}

    steps:
      # Ensure that windows machines support long paths
      - name: git Long File Path Support on Windows
        if: ${{ startsWith(inputs.operating_system, 'windows') }}
        run: |
          git config --system core.longpaths true

      - name: "Checkout Source"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize
        id: Initialize
        uses: davidbrownell/dbrownell_DevTools/.github/actions/initialize@CI-v0.22.1
        with:
          operating_system: ${{ inputs.operating_system }}

      # Note that this action is invoked in the original repository (e.g. not dbrownell_DevTools)
      - name: Custom Initialization (./.github/actions/initialize_validate_python)
        uses: ./.github/actions/initialize_validate_python
        if: ${{ hashFiles('.github/actions/initialize_validate_python/action.yml') != '' }}
        with:
          operating_system: ${{ inputs.operating_system }}
          python_version: ${{ inputs.python_version }}
          custom_initialization_secret: ${{ secrets.CUSTOM_INITIALIZATION_SECRET }}
          script_prefix: ${{ steps.initialize.outputs.script_prefix }}
          script_extension: ${{ steps.initialize.outputs.script_extension }}
          shell_name: ${{ steps.initialize.outputs.shell_name }}
          source_command: ${{ steps.initialize.outputs.source_command }}
          sudo_command: ${{ steps.initialize.outputs.sudo_command }}

      - name: Validate
        uses: davidbrownell/dbrownell_DevTools/.github/actions/validate_python_impl@CI-v0.22.1
        with:
          operating_system: ${{ inputs.operating_system }}
          python_version: ${{ inputs.python_version }}
          script_prefix: ${{ steps.initialize.outputs.script_prefix }}
          script_extension: ${{ steps.initialize.outputs.script_extension }}
          shell_name: ${{ steps.initialize.outputs.shell_name }}
          source_command: ${{ steps.initialize.outputs.source_command }}
          sudo_command: ${{ steps.initialize.outputs.sudo_command }}
