# ----------------------------------------------------------------------
# |
# |  callable_validate_python_binary.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2024-02-01 10:12:32
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2024
# |  Distributed under the MIT License.
# |
# ----------------------------------------------------------------------
name: "[impl] Validates Python Binary"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      operating_system:
        required: true
        type: string

      python_version:
        required: true
        type: string

      validation_command:
        required: true
        type: string

      # Specify a binary prefix if more than 1 binary is build within the repository. This value
      # will be one of the names that you defined in Build.py when calling
      # RepoBuildTools.Python.BuildBinariesFuncFactory, followed by a dash (e.g. "name1-" or
      # "name2-"). Do not specify a value if building a single binary within the repository.
      binary_prefix:
        required: false
        type: string

jobs:
  validate:
    name: Execute
    runs-on: ${{ inputs.operating_system }}

    steps:
      - name: Initialize
        id: Initialize
        uses: davidbrownell/dbrownell_DevTools/.github/actions/initialize@main
        with:
          operating_system: ${{ inputs.operating_system }}

      - name: Validate Binary
        uses: davidbrownell/dbrownell_DevTools/.github/actions/validate_python_binary_impl@main
        with:
          binary_prefix: ${{ inputs.binary_prefix }}
          operating_system: ${{ inputs.operating_system }}
          python_version: ${{ inputs.python_version }}
          validation_command: ${{ inputs.validation_command }}
          shell_name: ${{ steps.initialize.outputs.shell_name }}
