# ----------------------------------------------------------------------
# |
# |  callable_publish_python.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2024-01-27 10:27:57
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2024
# |  Distributed under the MIT License.
# |
# ----------------------------------------------------------------------
name: "[Callable] Publish Python Packages"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      release_sources_configuration_filename:
        description: "The name of the file that contains the file and direcotry configurations to trigger new releases."
        required: true
        type: string

    secrets:
      PYPI_TOKEN:
        required: true

jobs:
  publish:
    name: Execute
    runs-on: ubuntu-latest

    env:
      COLUMNS: "200"
      SIMULATE_TERMINAL_CAPABILITIES_SUPPORTS_COLORS: "1"
      PYTHONIOENCODING: "UTF-8"
      GH_TOKEN: ${{ github.token }}

    steps:
      # Ensure that windows machines support long paths
      - name: git Long File Path Support on Windows
        if: ${{ startsWith(inputs.operating_system, 'windows') && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          git config --system core.longpaths true

      - name: "Checkout Source"
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Has Release Changes?
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: dorny/paths-filter@v3
        id: has_release_changes
        with:
          filters: ${{ inputs.release_sources_configuration_filename }}

      - name: Initialize
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.has_release_changes.outputs.src == 'true' }}
        id: Initialize
        uses: davidbrownell/dbrownell_DevTools/.github/actions/initialize@CI-v0.15.5
        with:
          operating_system: ${{ inputs.operating_system }}

      - name: Publish
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.has_release_changes.outputs.src == 'true' }}
        uses: davidbrownell/dbrownell_DevTools/.github/actions/publish_python_impl@CI-v0.15.5
        with:
          script_prefix: ${{ steps.initialize.outputs.script_prefix }}
          script_extension: ${{ steps.initialize.outputs.script_extension }}
          shell_name: ${{ steps.initialize.outputs.shell_name }}
          source_command: ${{ steps.initialize.outputs.source_command }}
          sudo_command: ${{ steps.initialize.outputs.sudo_command }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}
