# ----------------------------------------------------------------------
# |
# |  callable_validate_python_binary.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2024-02-01 10:12:32
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2024
# |  Distributed under the MIT License.
# |
# ----------------------------------------------------------------------
name: "[Callable] Validate Python Binary"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      operating_system:
        required: true
        type: string

      python_version:
        required: true
        type: string

      validation_command:
        required: true
        type: string

      # Specify a binary prefix if more than 1 binary is build within the repository. This value
      # will be one of the names that you defined in Build.py when calling
      # RepoBuildTools.Python.BuildBinariesFuncFactory, followed by a dash (e.g. "name1-" or
      # "name2-"). Do not specify a value if building a single binary within the repository.
      binary_prefix:
        required: false
        type: string

    secrets:
      CUSTOM_INITIALIZATION_SECRET:
        required: false

jobs:
  validate:
    name: Execute
    runs-on: ${{ inputs.operating_system }}

    permissions: {}

    steps:
      - name: Initialize
        id: Initialize
        uses: davidbrownell/dbrownell_DevTools/.github/actions/initialize@CI-v0.22.1
        with:
          operating_system: ${{ inputs.operating_system }}

      # Note that this action is invoked in the original repository (e.g. not dbrownell_DevTools)
      - name: Custom Initialization (./.github/actions/initialize_validate_python_binary)
        uses: ./.github/actions/initialize_validate_python_binary
        if: ${{ hashFiles('.github/actions/initialize_validate_python_binary/action.yml') != '' }}
        with:
          operating_system: ${{ inputs.operating_system }}
          python_version: ${{ inputs.python_version }}
          custom_initialization_secret: ${{ secrets.CUSTOM_INITIALIZATION_SECRET }}
          script_prefix: ${{ steps.initialize.outputs.script_prefix }}
          script_extension: ${{ steps.initialize.outputs.script_extension }}
          shell_name: ${{ steps.initialize.outputs.shell_name }}
          source_command: ${{ steps.initialize.outputs.source_command }}
          sudo_command: ${{ steps.initialize.outputs.sudo_command }}

      - name: Validate Binary
        uses: davidbrownell/dbrownell_DevTools/.github/actions/validate_python_binary_impl@CI-v0.22.1
        with:
          binary_prefix: ${{ inputs.binary_prefix }}
          operating_system: ${{ inputs.operating_system }}
          python_version: ${{ inputs.python_version }}
          validation_command: ${{ inputs.validation_command }}
          shell_name: ${{ steps.initialize.outputs.shell_name }}
