# ----------------------------------------------------------------------
# |
# |  callable_python_publish.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2024-01-27 10:27:57
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2024
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "[impl] Publishes Python Packages"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  workflow_call:

jobs:
  publish:
    name: Execute
    runs-on: ubuntu-latest

    env:
      COLUMNS: "200"
      SIMULATE_TERMINAL_CAPABILITIES_SUPPORTS_COLORS: "1"
      PYTHONIOENCODING: "UTF-8"
      GH_TOKEN: ${{ github.token }}

    steps:
      # Ensure that windows machines support long paths
      - name: git Long File Path Support on Windows
        if: ${{ startsWith(inputs.operating_system, 'windows') }}
        run: |
          git config --system core.longpaths true

      - name: "Checkout Source"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize
        id: Initialize
        uses: davidbrownell/dbrownell_DevTools/.github/actions/initialize@main
        with:
          operating_system: ${{ inputs.operating_system }}

      - name: Has Source Changes?
        uses: dorny/paths-filter@v3
        id: has_code_changes
        with:
          filters: |
            src:
              - 'src/**'

      - name: Publish
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.has_code_changes.outputs.src == 'true' }}
        uses: davidbrownell/dbrownell_DevTools/.github/actions/python_publish_impl@TemporaryCI # TODO: main
        with:
          script_prefix: ${{ steps.initialize.outputs.script_prefix }}
          script_extension: ${{ steps.initialize.outputs.script_extension }}
          shell_name: ${{ steps.initialize.outputs.shell_name }}
          source_command: ${{ steps.initialize.outputs.source_command }}
          sudo_command: ${{ steps.initialize.outputs.sudo_command }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}
