# ----------------------------------------------------------------------
# |
# |  callable_create_docker_image.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2024-02-15 13:02:01
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2024
# |  Distributed under the MIT License.
# |
# ----------------------------------------------------------------------
name: "[Callable] Create Docker Image"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      operating_system:
        required: true
        type: string

      python_version:
        required: true
        type: string

      name_suffix:
        # Optional suffix applied to the image tag
        required: false
        type: string
        default: ""

      docker_description:
        # Optional description embedded in the generated image
        required: false
        type: string
        default: ""

      bootstrap_args:
        # Optional arguments provided to the Bootstrap script within the image
        required: false
        type: string
        default: ""

      push_image_as_package:
        required: false
        type: boolean
        default: false

      container_registry_username:
        required: false
        type: string
        default: ""

    secrets:
      CUSTOM_INITIALIZATION_SECRET:
        required: false

      CUSTOM_DESTRUCTION_SECRET:
        required: false

jobs:
  docker_image:
    name: Execute
    runs-on: ${{ inputs.operating_system }}

    env:
      COLUMNS: "200"
      SIMULATE_TERMINAL_CAPABILITIES_SUPPORTS_COLORS: "1"
      PYTHONIOENCODING: "UTF-8"

    permissions:
      packages: write  # To publish the image

    steps:
      # Ensure that windows machines support long paths
      - name: git Long File Path Support on Windows
        if: ${{ startsWith(inputs.operating_system, 'windows') }}
        run: |
          git config --system core.longpaths true

      - name: "Checkout Source"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize
        id: Initialize
        uses: davidbrownell/dbrownell_DevTools/.github/actions/initialize@CI-v0.24.0
        with:
          operating_system: ${{ inputs.operating_system }}

      # Note that this action is invoked in the original repository (e.g. not dbrownell_DevTools)
      - name: Custom Initialization (./.github/actions/initialize_create_docker_image)
        uses: ./.github/actions/initialize_create_docker_image
        if: ${{ hashFiles('.github/actions/initialize_create_docker_image/action.yml') != '' }}
        with:
          operating_system: ${{ inputs.operating_system }}
          python_version: ${{ inputs.python_version }}
          custom_initialization_secret: ${{ secrets.CUSTOM_INITIALIZATION_SECRET }}
          script_prefix: ${{ steps.initialize.outputs.script_prefix }}
          script_extension: ${{ steps.initialize.outputs.script_extension }}
          shell_name: ${{ steps.initialize.outputs.shell_name }}
          source_command: ${{ steps.initialize.outputs.source_command }}
          sudo_command: ${{ steps.initialize.outputs.sudo_command }}

      - name: Create Docker Image
        uses: davidbrownell/dbrownell_DevTools/.github/actions/create_docker_image_impl@CI-v0.24.0
        with:
          name_suffix: ${{ inputs.name_suffix }}
          docker_description: ${{ inputs.docker_description }}
          push_image_as_package: ${{ inputs.push_image_as_package }}
          container_registry_username: ${{ inputs.container_registry_username }}
          container_registry_password: ${{ secrets.GITHUB_TOKEN }}
          bootstrap_args: ${{ inputs.bootstrap_args }}
          operating_system: ${{ inputs.operating_system }}
          python_version: ${{ inputs.python_version }}
          script_prefix: ${{ steps.initialize.outputs.script_prefix }}
          script_extension: ${{ steps.initialize.outputs.script_extension }}
          shell_name: ${{ steps.initialize.outputs.shell_name }}
          source_command: ${{ steps.initialize.outputs.source_command }}
          compressed_extension: ${{ steps.initialize.outputs.compressed_extension }}

      # Note that this action is invoked in the original repository (e.g. not dbrownell_DevTools)
      - name: Custom Destruction (./.github/actions/destroy_create_docker_image)
        uses: ./.github/actions/destroy_create_docker_image
        if: ${{ hashFiles('.github/actions/destroy_create_docker_image/action.yml') != '' }}
        with:
          operating_system: ${{ inputs.operating_system }}
          python_version: ${{ inputs.python_version }}
          custom_destruction_secret: ${{ secrets.CUSTOM_DESTRUCTION_SECRET }}
          script_prefix: ${{ steps.initialize.outputs.script_prefix }}
          script_extension: ${{ steps.initialize.outputs.script_extension }}
          shell_name: ${{ steps.initialize.outputs.shell_name }}
          source_command: ${{ steps.initialize.outputs.source_command }}
          sudo_command: ${{ steps.initialize.outputs.sudo_command }}
