# ----------------------------------------------------------------------
# |
# |  callable_validate_python_package.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2024-02-01 09:30:45
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2024
# |  Distributed under the MIT License.
# |
# ----------------------------------------------------------------------
name: "[impl] Validates Python Package"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      operating_system:
        required: true
        type: string

      python_version:
        required: true
        type: string

      validation_command:
        required: true
        type: string

jobs:
  validate:
    name: Execute
    runs-on: ${{ inputs.operating_system }}

    steps:
      - name: Initialize
        id: Initialize
        uses: davidbrownell/dbrownell_DevTools/.github/actions/initialize@main
        with:
          operating_system: ${{ inputs.operating_system }}

      - name: Validate Package
        uses: davidbrownell/dbrownell_DevTools/.github/actions/validate_python_package_impl@main
        with:
          operating_system: ${{ inputs.operating_system }}
          python_version: ${{ inputs.python_version }}
          validation_command: ${{ inputs.validation_command }}
          shell_name: ${{ steps.initialize.outputs.shell_name }}
