# ----------------------------------------------------------------------
# |
# |  callable_validate_python_package.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2024-02-01 09:30:45
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2024
# |  Distributed under the MIT License.
# |
# ----------------------------------------------------------------------
name: "[Callable] Validate Python Package"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      operating_system:
        required: true
        type: string

      python_version:
        required: true
        type: string

      validation_command:
        required: true
        type: string

    secrets:
      CUSTOM_INITIALIZATION_SECRET:
        required: false

      CUSTOM_DESTRUCTION_SECRET:
        required: false

jobs:
  validate:
    name: Execute
    runs-on: ${{ inputs.operating_system }}

    permissions: {}

    steps:
      - name: Initialize
        id: Initialize
        uses: davidbrownell/dbrownell_DevTools/.github/actions/initialize@CI-v0.22.2
        with:
          operating_system: ${{ inputs.operating_system }}

      # Note that this action is invoked in the original repository (e.g. not dbrownell_DevTools)
      - name: Custom Initialization (./.github/actions/initialize_validate_python_package)
        uses: ./.github/actions/initialize_validate_python_package
        if: ${{ hashFiles('.github/actions/initialize_validate_python_package/action.yml') != '' }}
        with:
          operating_system: ${{ inputs.operating_system }}
          python_version: ${{ inputs.python_version }}
          custom_initialization_secret: ${{ secrets.CUSTOM_INITIALIZATION_SECRET }}
          script_prefix: ${{ steps.initialize.outputs.script_prefix }}
          script_extension: ${{ steps.initialize.outputs.script_extension }}
          shell_name: ${{ steps.initialize.outputs.shell_name }}
          source_command: ${{ steps.initialize.outputs.source_command }}
          sudo_command: ${{ steps.initialize.outputs.sudo_command }}

      - name: Validate Package
        uses: davidbrownell/dbrownell_DevTools/.github/actions/validate_python_package_impl@CI-v0.22.2
        with:
          operating_system: ${{ inputs.operating_system }}
          python_version: ${{ inputs.python_version }}
          validation_command: ${{ inputs.validation_command }}
          shell_name: ${{ steps.initialize.outputs.shell_name }}

      # Note that this action is invoked in the original repository (e.g. not dbrownell_DevTools)
      - name: Custom Destruction (./.github/actions/destroy_validate_python_package)
        uses: ./.github/actions/destroy_validate_python_package
        if: ${{ hashFiles('.github/actions/destroy_validate_python_package/action.yml') != '' }}
        with:
          operating_system: ${{ inputs.operating_system }}
          python_version: ${{ inputs.python_version }}
          custom_destruction_secret: ${{ secrets.CUSTOM_DESTRUCTION_SECRET }}
          script_prefix: ${{ steps.initialize.outputs.script_prefix }}
          script_extension: ${{ steps.initialize.outputs.script_extension }}
          shell_name: ${{ steps.initialize.outputs.shell_name }}
          source_command: ${{ steps.initialize.outputs.source_command }}
          sudo_command: ${{ steps.initialize.outputs.sudo_command }}
